CREATE TABLE [dbo].[Email]
(
	[Id] INT NOT NULL IDENTITY (1, 1) PRIMARY KEY CLUSTERED,
	MessageId VARCHAR(MAX) NOT NULL,
	ImportedOn DATETIME NOT NULL,
	ReceivedOn DATETIME NOT NULL,
	[From] VARCHAR(200) NOT NULL,
	[Subject] NVARCHAR(MAX) NULL,
	[Body] NVARCHAR(MAX) NULL
)
