CREATE TABLE [dbo].[Inbox]
(
	[Id] INT NOT NULL IDENTITY (1, 1) PRIMARY KEY CLUSTERED,
	CreatedOn DATETIME NOT NULL,
	[Email] VARCHAR(200) NOT NULL,
	[Name] NVARCHAR(200) NULL,
	INDEX UX_Inbox_Email UNIQUE (Email)
)
